version: "3.8"
services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "../data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  structurizr-lite:
    image: "structurizr/lite:latest"
    container_name: structurizr-lite
    ports:
      - "8080:8080"
    volumes:
      - "../docs/c4/01-from-crud-to-cqrs/step-00-crud:/usr/local/structurizr"
      # - "../docs/c4/01-from-crud-to-cqrs/step-01-better-crud:/usr/local/structurizr"
      # - "../docs/c4/01-from-crud-to-cqrs/step-02-cqrs:/usr/local/structurizr"
      # - "../docs/c4/01-from-crud-to-cqrs/step-03-cqrs-with-ports-and-adapters:/usr/local/structurizr"
      # - "../docs/c4/02-deploying-cqrs-in-aws-lambda-environment/approach-00-monolithic-dispatcher:/usr/local/structurizr"
      # - "../docs/c4/02-deploying-cqrs-in-aws-lambda-environment/approach-01-commands-and-queries-dispatchers:/usr/local/structurizr"
      # - "../docs/c4/02-deploying-cqrs-in-aws-lambda-environment/approach-02-extract-subdomain-commands-or-subdomain-queries:/usr/local/structurizr"
      # - "../docs/c4/02-deploying-cqrs-in-aws-lambda-environment/approach-03-extract-individual-commands-or-queries:/usr/local/structurizr"
      # - "../docs/c4/02-deploying-cqrs-in-aws-lambda-environment/approach-04-full-separation:/usr/local/structurizr"
    working_dir: /usr/local/structurizr
