AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  'Hello World' AWS Lambda in TypeScript

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  LayerCommons:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      ContentUri: layers/commons/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Delete

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        External:
          - commons
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app/handler.ts
    Properties:
      CodeUri: library/
      Handler: handler.main
      Layers:
        - !Ref LayerCommons
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        AuthorGET:
          Type: Api
          Properties:
            Path: /author
            Method: get
        BookGET:
          Type: Api
          Properties:
            Path: /book
            Method: get
        UserGET:
          Type: Api
          Properties:
            Path: /user
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub: "ApplicationInsights-SAM-${AWS::StackName}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:

  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
